### PR TITLE
subghz: Allow custom lora sync word

### PR DESCRIPTION
**Pull request by huming2207**
Hi @newAM 

Firstly thanks again for your great effort for this library!

We are trying to use this library to implement a factory testing firmware for our LoRa products. The current implementation doesn't allow us to configure custom LoRa sync word, so our LoRa protocol won't work. Therefore I implemented this feature to make it fit to our use cases.

Regards,
Jackson

### CODE REVIEW

**Comment by newAM** [comment]
Oh boy, CI really hasn't been run in a while.  I'll take a look at that this weekend.

**Comment by huming2207** [comment]
In regards to the changes, I'm also thinking to add a few more `From<&[u8]>` impls to those LoRa/GFSK config structs. For example imagine I've got a `From<&[u8]>` that allows `let pkt_params = LoRaPacketParams::from(some_slice);` so that I can pass pre-serialised config data over UART or SWD into the target for testing. 

Are you interested? If yes then I will also push a separate PR. @newAM

**Comment by huming2207** [comment]
@newAM any updates on this...?

**Comment by huming2207** [comment]
> No worries! Can you update this branch? Then CI should start to work again.

It should work now.

**Review by newAM — APPROVED** [review]
Thanks!  Sorry for the delay, work has been crazy lately.

**Comment by huming2207** [comment]
@newAM thanks!

> In regards to the changes, I'm also thinking to add a few more From<&[u8]> impls to those LoRa/GFSK config structs. For example imagine I've got a From<&[u8]> that allows let pkt_params = LoRaPacketParams::from(some_slice); so that I can pass pre-serialised config data over UART or SWD into the target for testing.

Also I would like to know are you interested in more PRs? For example the STOP2 low power mode, LPUART's FIFO mode, and these `From<&[u8]>` stuff mentioned above?

I need the STOP1/STOP2 mode to work in my project, and I'm also keen on do some researches on LPUART FIFO mode.

**Comment by newAM** [comment]
Yeah!  I'm definitively interested in more PRs, it just may take me a while to get to them :)

**Comment by huming2207** [comment]
Great, will do later.

**Pull request merged**
